INSERT INTO model_configs (
  id,
  model_key,
  display_name,
  provider,
  enabled,
  is_default,
  max_context_tokens,
  supports_web_search,
  supports_reasoning,
  supports_file_qa,
  supports_stream,
  input_price_per_1k,
  output_price_per_1k,
  config_json,
  created_at,
  updated_at
)
VALUES
  (
    gen_random_uuid(),
    'deepseek-ai/DeepSeek-V3',
    'DeepSeek V3',
    'siliconflow',
    true,
    true,
    64000,
    true,
    true,
    true,
    true,
    0.002000,
    0.004000,
    '{"temperatureRange":[0,1],"supportsThinking":true}'::jsonb,
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'Qwen/Qwen2.5-72B-Instruct',
    'Qwen2.5 72B Instruct',
    'siliconflow',
    true,
    false,
    64000,
    true,
    false,
    true,
    true,
    0.003000,
    0.006000,
    '{"temperatureRange":[0,1],"supportsThinking":false}'::jsonb,
    now(),
    now()
  )
ON CONFLICT (model_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  provider = EXCLUDED.provider,
  enabled = EXCLUDED.enabled,
  is_default = EXCLUDED.is_default,
  max_context_tokens = EXCLUDED.max_context_tokens,
  supports_web_search = EXCLUDED.supports_web_search,
  supports_reasoning = EXCLUDED.supports_reasoning,
  supports_file_qa = EXCLUDED.supports_file_qa,
  supports_stream = EXCLUDED.supports_stream,
  input_price_per_1k = EXCLUDED.input_price_per_1k,
  output_price_per_1k = EXCLUDED.output_price_per_1k,
  config_json = EXCLUDED.config_json,
  updated_at = now();
